// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"context"
)

type Querier interface {
	CreateMerchant(ctx context.Context, arg CreateMerchantParams) (Merchant, error)
	CreateTransaction(ctx context.Context, arg CreateTransactionParams) (Transaction, error)
	PaginateAscMerchants(ctx context.Context, arg PaginateAscMerchantsParams) ([]Merchant, error)
	//
	// Paginate - Control
	//
	PaginateCountMerchants(ctx context.Context, merchantName string) (int64, error)
	PaginateDescMerchants(ctx context.Context, arg PaginateDescMerchantsParams) ([]Merchant, error)
	ReadMerchant(ctx context.Context, merchantID int32) (Merchant, error)
	TransactionsEarns(ctx context.Context) (float64, error)
	TransactionsEarnsByMerchant(ctx context.Context, merchantID int32) (float64, error)
	UpdateMerchant(ctx context.Context, arg UpdateMerchantParams) (Merchant, error)
}

var _ Querier = (*Queries)(nil)
