// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: reports.sql

package db

import (
	"context"
)

const transactionsEarns = `-- name: TransactionsEarns :one
SELECT SUM(fee)::double precision AS total_earns FROM transactions
`

func (q *Queries) TransactionsEarns(ctx context.Context) (float64, error) {
	row := q.db.QueryRow(ctx, transactionsEarns)
	var total_earns float64
	err := row.Scan(&total_earns)
	return total_earns, err
}

const transactionsEarnsByMerchant = `-- name: TransactionsEarnsByMerchant :one
SELECT SUM(fee)::double precision AS total_earns FROM transactions WHERE "merchant_id" = $1
`

func (q *Queries) TransactionsEarnsByMerchant(ctx context.Context, merchantID int32) (float64, error) {
	row := q.db.QueryRow(ctx, transactionsEarnsByMerchant, merchantID)
	var total_earns float64
	err := row.Scan(&total_earns)
	return total_earns, err
}
