// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: transactions.sql

package db

import (
	"context"
)

const createTransaction = `-- name: CreateTransaction :one
INSERT INTO transactions ("merchant_id", "amount", "commission", "fee") 
VALUES ($1, $2, $3, $4) RETURNING transaction_id, merchant_id, amount, commission, fee, created_at, updated_at
`

type CreateTransactionParams struct {
	MerchantID int32   `json:"merchant_id"`
	Amount     float64 `json:"amount"`
	Commission float64 `json:"commission"`
	Fee        float64 `json:"fee"`
}

func (q *Queries) CreateTransaction(ctx context.Context, arg CreateTransactionParams) (Transaction, error) {
	row := q.db.QueryRow(ctx, createTransaction,
		arg.MerchantID,
		arg.Amount,
		arg.Commission,
		arg.Fee,
	)
	var i Transaction
	err := row.Scan(
		&i.TransactionID,
		&i.MerchantID,
		&i.Amount,
		&i.Commission,
		&i.Fee,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
